server:
  port: 7272

spring:
  profiles:
    active:
      - local
  kafka:
    client-id: alison
    template:
      default-topic: topic.voting

  jackson:
    deserialization:
      fail-on-unknown-properties: true

---

spring:
  config:
    activate:
      on-profile:
        - local

  kafka:
    bootstrap-servers: localhost:9092

